package za.co.vlugboek.domain;

public enum ClassificationCategory {
    HOK_PUNTE,
    OPE_PUNTE,
    LEDE_PUNTE,
    JO_PUNTE,
    SHORT_DISTANCE,
    MIDDLE_DISTANCE,
    LONG_DISTANCE,
    COMBINE_BIRDS_LOG_SHORT_DISTANCE_ALL_RACES,
    COMBINE_BIRDS_LOG_SHORT_DISTANCE_OPEN_RACES,
    COMBINE_BIRDS_LOG_SHORT_DISTANCE_YEARLING_RACES,
    COMBINE_SHORT_DISTANCE_LOG_ALL_RACES,
    COMBINE_SHORT_DISTANCE_LOG_OPEN_RACES,
    COMBINE_SHORT_DISTANCE_LOG_YEARLING_RACES,
    COMBINE_OVERALL_LOG_ALL_RACES,
    COMBINE_OVERALL_LOG_OPEN_RACES,
    COMBINE_OVERALL_LOG_YEARLING_RACES,
    NONE
}
