create table federations (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    country varchar(255) not null,
    name varchar(255) not null,
    constraint uk_federations_code unique (code)
);

create table clubs (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    federation_id bigint not null,
    constraint fk_clubs_federation foreign key (federation_id) references federations (id)
);

create table lofts (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    club_id bigint not null,
    constraint fk_lofts_club foreign key (club_id) references clubs (id)
);

create table app_users (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    display_name varchar(255) not null,
    email varchar(255) not null,
    language varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    session_token varchar(255),
    club_id bigint,
    federation_id bigint,
    loft_id bigint,
    constraint uk_app_users_email unique (email),
    constraint fk_app_users_club foreign key (club_id) references clubs (id),
    constraint fk_app_users_federation foreign key (federation_id) references federations (id),
    constraint fk_app_users_loft foreign key (loft_id) references lofts (id)
);

create table documents (
    id bigint generated by default as identity primary key,
    available_to_users boolean not null,
    classification_category varchar(255) not null,
    content_type varchar(255),
    file_size bigint not null,
    imported_at timestamp(6) with time zone,
    liberated_at timestamp(6),
    official_date date,
    original_filename varchar(255) not null,
    recognised_type varchar(255),
    report_created_at timestamp(6),
    report_family varchar(255) not null,
    status varchar(255) not null,
    stored_path varchar(1000) not null,
    title varchar(255) not null,
    uploaded_at timestamp(6) with time zone not null,
    club_names varchar(10000),
    loft_names varchar(10000),
    race_point varchar(255),
    search_index varchar(20000),
    federation_id bigint,
    constraint fk_documents_federation foreign key (federation_id) references federations (id)
);

create table report_datasets (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    official_date date,
    report_family varchar(255) not null,
    title varchar(255) not null,
    document_id bigint not null,
    constraint uk_report_datasets_document unique (document_id),
    constraint fk_report_datasets_document foreign key (document_id) references documents (id)
);

create table report_columns (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    position_index integer not null,
    dataset_id bigint not null,
    constraint fk_report_columns_dataset foreign key (dataset_id) references report_datasets (id)
);

create table report_rows (
    id bigint generated by default as identity primary key,
    row_index integer not null,
    dataset_id bigint not null,
    constraint fk_report_rows_dataset foreign key (dataset_id) references report_datasets (id)
);

create table report_cells (
    id bigint generated by default as identity primary key,
    column_index integer not null,
    text_value varchar(2000),
    row_id bigint not null,
    constraint fk_report_cells_row foreign key (row_id) references report_rows (id)
);

create table classification_snapshots (
    id bigint generated by default as identity primary key,
    category varchar(255) not null,
    latest boolean not null,
    snapshot_date date not null,
    dataset_id bigint not null,
    constraint fk_classification_snapshots_dataset foreign key (dataset_id) references report_datasets (id)
);

create table email_delivery_audits (
    id bigint generated by default as identity primary key,
    completed_at timestamp(6) with time zone,
    document_title varchar(255) not null,
    error_message varchar(2000),
    language varchar(12) not null,
    mailer_url varchar(1000),
    message_id varchar(255),
    provider_status_code integer,
    recipient_email varchar(255) not null,
    recipient_name varchar(255) not null,
    request_id varchar(255),
    requested_at timestamp(6) with time zone not null,
    status varchar(255) not null,
    document_id bigint not null,
    user_id bigint not null,
    constraint fk_email_delivery_audits_document foreign key (document_id) references documents (id),
    constraint fk_email_delivery_audits_user foreign key (user_id) references app_users (id)
);

create index idx_clubs_federation on clubs (federation_id);
create index idx_lofts_club on lofts (club_id);
create index idx_app_users_federation on app_users (federation_id);
create index idx_app_users_club on app_users (club_id);
create index idx_app_users_loft on app_users (loft_id);
create index idx_documents_federation on documents (federation_id);
create index idx_documents_status on documents (status);
create index idx_documents_family_category on documents (report_family, classification_category);
create index idx_documents_official_date on documents (official_date);
create index idx_report_datasets_document on report_datasets (document_id);
create index idx_report_columns_dataset on report_columns (dataset_id);
create index idx_report_rows_dataset on report_rows (dataset_id);
create index idx_report_cells_row on report_cells (row_id);
create index idx_classification_snapshots_category_latest on classification_snapshots (category, latest);
create index idx_email_delivery_audits_document on email_delivery_audits (document_id);
create index idx_email_delivery_audits_user on email_delivery_audits (user_id);
