create table ingestion_runs (
    id bigint generated by default as identity primary key,
    completed_at timestamp(6) with time zone,
    duplicate_count integer not null,
    failed_count integer not null,
    imported_count integer not null,
    inbox_path varchar(1000) not null,
    rejected_count integer not null,
    report_path varchar(1000),
    started_at timestamp(6) with time zone not null,
    status varchar(255) not null,
    suspect_count integer not null,
    total_files integer not null,
    started_by_user_id bigint,
    constraint fk_ingestion_runs_started_by foreign key (started_by_user_id) references app_users (id)
);

create table ingestion_items (
    id bigint generated by default as identity primary key,
    archive_path varchar(1000),
    column_count integer,
    content_sha256 varchar(64),
    file_size bigint,
    filename varchar(255) not null,
    message varchar(2000),
    recognised_type varchar(255),
    report_family varchar(255),
    row_count integer,
    source_path varchar(1000),
    status varchar(255) not null,
    title varchar(255),
    warnings varchar(2000),
    document_id bigint,
    run_id bigint not null,
    constraint fk_ingestion_items_document foreign key (document_id) references documents (id),
    constraint fk_ingestion_items_run foreign key (run_id) references ingestion_runs (id)
);

create index idx_ingestion_runs_started_at on ingestion_runs (started_at);
create index idx_ingestion_items_run on ingestion_items (run_id);
create index idx_ingestion_items_document on ingestion_items (document_id);
